language: node_js
sudo: required
dist: trusty

# Blocklist
branches:
  except:
    - gh-pages # will be deployed to, no need to build it

stages:
  - release
  - deploy

jobs:
  include:
    # Job: Release
    - stage: release
      if: branch = master
      node_js:
        - 'lts/*'
      skip_cleanup: true
      script:
        - npx semantic-release

    # Job: Page
    - stage: deploy
      if: branch = master
      node_js:
        - 'lts/*'
      script:
        - git fetch --tags
        - version=$(git describe --tags `git rev-list --tags --max-count=1`)
        - echo "Documentation version $version"
        - git checkout refs/tags/${version}
        - chmod +x ./styleguide/prepare.sh
        - ./styleguide/prepare.sh
        - npm run styleguide:build
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
          keep_history: true
          local_dir: public/
